---
apiVersion: apps/api
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: messaging-app
      labels:
        app: django
    spec:
      containers:
        - name: messaging_app
          image: mesaging_app-web:latest  
          ports:
            containerPort: 8000

---
apiVersion: api
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      tartgetPort: 8000

