pipeline {
    agent { 
        node {
            label 'jenkins-agent-goes-here'
            }
      }
      triggers {
          pollSCM '* * * * *'
          }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                cd messaging_app

                pip install -r requirement.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd messaging_app
                pytest
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                '''
            }
        }
    }
}
