pipeline {
    agent {
        // use a clean python environment on every build
        docker { image 'python 3.9-slim'}
        }
    stages {
        stage('Install Dependencies') {
            steps {
                echo "Installing dependencies....."
                sh '''

                python3 -m pip install -r messaging_app/requirement.txt
                '''
                }

            }
            }
        stage('Test') {
            steps {
                echo "Runing tests..."
                sh '''
                python3 -m pytest messaging_app/ --junitxml=report.xml
                '''
            }
        }
    post {
        always {
            junit 'report.xml'
            }
        }
}
