name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name:   Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r messaging_app/requirements.txt
        pip install flake8 pytest-conv

    - name: Lint with flake8
      run: |
        # stop the build if there are sysntx errors or undefined names
        flake8 messaging_app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        flake8 messaging_app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with Pytest and generate coverage
      run: |
        pytest --cov=messaging_app --cov-report=xml

    - name: Upload coverage to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
