---
apiVersion: apps/api
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: messaging-app
      labels:
        app: django
    spec:
      containers:
        - name: Python
          image: python:3.14
          ports:
            containerPort: 8000

