services:
  db:
    image: mysql:8.0
    container_name: messaging_db_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    container_name: messaging_web_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
       DB_HOST: db
       DB_PORT: ${DB_PORT}
       MYSQL_DATABASEi: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
