pipeline {
    agent { 
        node { 
            label 'New-Node'
        }
        
    }
    stages {
        stage('Install Dependencies') {
            steps {
                echo "Installing dependencies..."
                // Use python3 to be explicit
                sh '''
                    
                python3 -m venv venv
                venv/bin/pip3 install -r messaging_app/requirements.txt

                '''
            }
        }
        stage('Test') {
            steps {
                echo "Running tests..."
                // Generate a JUnit XML report
                // Note: I've added the path to your code within the workspace
                sh 'venv/bin/pytest messaging_app/ --junitxml=report.xml'
            }
        }
    }
    post {
        // This block runs after all stages are complete
        always {
            // deleteDir 'venv'
            // Archive the test results
            junit 'report.xml'
        }
    }
}
