pipeline {
    agent any 
      triggers {
          pollSCM '* * * * *'
          }
    stages {
        stage('git set-up and cleanup') {
            steps {
                echo "Repo setup"
                sh '''
                git clone https://github.com/AlexNduta/alx-backend-python.git

                cd messaging_app
                '''
                }

            }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                pip3 install -r messaging_app/requirement.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                pytest
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                '''
            }
        }
    }
}
