#!/usr/bin/bash


echo "Starting minikube cluster, this may take a momnet"
minikube start


echo "verrifying cluster status..."
kubectl cluster-info

echo "Getting available pods"
kubectl get pods --all-namespaces



